apiVersion: v1
kind: Service
metadata:
  name: inference-backend
  labels:
    app: inference-backend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 11434
    protocol: TCP
  selector:
    app: inference-backend
