apiVersion: apps/v1
kind: Deployment
metadata:
  name: embed-service
  labels:
    app: embed-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: embed-service
  template:
    metadata:
      labels:
        app: embed-service
    spec:
      containers:
        - name: embed-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
          env:
            - name: EMBED_CONCURRENCY
              value: "{{ .Values.env.EMBED_CONCURRENCY }}"
            - name: EMBED_HTTP_PORT
              value: "{{ .Values.env.EMBED_HTTP_PORT }}"
            - name: EMBED_PORT
              value: "{{ .Values.env.EMBED_PORT }}"
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
