apiVersion: v1
kind: Service
metadata:
  name: caw-wrapper
  labels:
    app: caw-wrapper
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: caw-wrapper
