apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: caw-wrapper
spec:
  scaleTargetRef:
    name: caw-wrapper
  minReplicaCount: 0
  maxReplicaCount: 20
  cooldownPeriod: 30
  fallback:
    failureThreshold: 3
    replicas: 3
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus:9090
      metricName: caw_requests_in_flight
      query: sum(caw_requests_in_flight)
      threshold: "5"
  authenticationRef:
    name: keda-trigger-auth-redis
